export const FETCH = {
  INIT: 'INIT',
  SUCCESS: 'SUCCES',
  FAILURE: 'FAILURE',
  LOAD: 'LOAD',
};
export const USER = {
  PIN: 'PIN',
  UN_PIN: 'UN_PIN',
  ACTIVE_PROFILE: 'ACTIVE_PROFILE',
  UN_ACTIVE_PROFILE: 'UN_ACTIVE_PROFILE',
};
